.TH "cmd20" "1" "0.1.2" "ekultails@gmail.com" "Amusements/Games"
.SH "cmd20"
.LP 
cmd20 \- A free and open source dice roller CLI utility programmed in C.
.SH "DESCRIPTION"
.LP 
This program can roll (or generate) any random number based on the provided input. 
.SH "OPTIONS"
.LP 
.TP 
\fB\-n\fR <\fInumber\fP>
Generates a random number between 1 and <\fInumber\fP>.
.TP 
\fB\-q\fR
Quiet mode only outputs the end result.
.TP 
\fB\-h\fR
Output help information and exit.
.TP 
\fB\-v\fR
Output version information and exit.
.SH "EXAMPLES"
.LP 
To run roll a d20:
.LP 
# cmd20 \-n 20
.LP 
For only seeing the rolled result: 
.LP 
# cmd20 \-q \-n 12
.SH "AUTHORS"
.LP 
ekultails@gmail.com
.SH "SEE ALSO"
.LP 
https://github.com/ekultails
